### ISSUE TITLE
symfony/console v4+ compatibility

### ISSUE THREAD

**Issue by spotman** [graze/supervisor#5]
Hi there!

Currently it is not possible to use supervisor in a project with the latest `symfony/console` (composer can not resolve dependencies). Do you have any plans for making `graze/supervisor` compatible with `symfony/console` v4 and up?

**Comment by biggianteye** [comment]
Thanks for the report. This is fixed in [1.2.0](https://github.com/graze/supervisor/releases/tag/1.2.0).
